
auth:
  - user: foo
    group: foo
    uid: 1000
    gid: 1000
    password: bar

global:
  - "force user = foo"
  - "force group = foo"

share:

  - name: share
    path: /samba/share
    browsable: yes
    readonly: no
    guestok: yes
    writelist: foo
    veto: no
  - name: foo
    path: /samba/foo
    browsable: yes
    readonly: no
    guestok: no
    validusers: foo
    writelist: foo
    veto: no
    hidefiles: /_*/
    recycle: yes
